apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-rollouts
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: devhub

  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-rollouts
      targetRevision: "2.37.7"
      helm:
        releaseName: argo-rollouts
        valueFiles:
          - $values/platform-sre/values/argo-rollouts-values.yaml

    - repoURL: https://github.com/rayanSalhi/pulse-campus.git
      targetRevision: main
      ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: argo-rollouts

  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true